server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username:
    password:
  liquibase:
    change-log: db-script/auth_server_schema.sql
