server:
  port: 9000

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org:
      springframework:
        jdbc: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: postgres
    password: 123456
  liquibase:
    change-log: db-script/auth_server_schema.sql
