server:
  port: 8082

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: clientB
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: read,openid
        provider:
          spring:
            issuer-uri: ${OAUTH2_CLIENT_ISSUER_URI:http://127.0.0.1:9000}

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: profile-route
          uri: ${PROFILE_SERVICE_URL:http://127.0.0.1:8080}
          predicates:
            - Path=/me
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
