server:
  port: 8080

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.jdbc: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_res
    username: postgres
    password: 123456
  liquibase:
    change-log: db-script/profile_schema.sql

  security:
    oauth2:
#      resourceserver.jwt.issuer-uri: http://localhost:9000
      resourceserver.jwt.jwk-set-uri: http://localhost:9000/oauth2/jwks
#      registration:
#        clientA:
#          clientId:
#          clientSecret:
#          redirectUri: http://localhost:8080/oauth2/callback/spring
#          scope:
#            - read
#            - write

#        google:
#          clientId: 16975348296-a6v9104lmm7phkht3cpflncp27q4eumn.apps.googleusercontent.com
#          clientSecret: AihYdRFI0BGnUBKFDBJLQ3mu
#          redirectUri: http://localhost:8080/oauth2/callback/google
#          scope:
#            - email
#            - profile
